export const articles = [
  {
    title: "Setup article 1",
    description: "desc 1",
    body: "body 1",
    tagList: ["setup"],
  },
  {
    title: "Setup article 2",
    description: "desc 2",
    body: "body 2",
    tagList: ["test"],
  },
  {
    title: "Setup article 3",
    description: "desc 3",
    body: "body 3",
    tagList: ["test1", "test2"],
  },
  {
    title: "Setup article 4",
    description: "desc 4",
    body: "body 4",
    tagList: ["test4", "test4"],
  },
  {
    title: "Setup article 5",
    description: "desc 5",
    body: "body 5",
    tagList: ["test5"],
  },
  {
    title: "Setup article 6",
    description: "desc 6",
    body: "body 6",
    tagList: ["test6"],
  },
  {
    title: "Setup article 7",
    description: "desc 7",
    body: "body 7",
    tagList: ["test7"],
  },
  {
    title: "Setup article 8",
    description: "desc 8",
    body: "body 8",
    tagList: ["test8"],
  },
  {
    title: "Setup article 9",
    description: "desc 9",
    body: "body 9",
    tagList: ["test9"],
  },
  {
    title: "Setup article 10",
    description: "desc 10",
    body: "body ",
    tagList: ["test10", "test10"],
  },
  {
    title: "Setup article 11",
    description: "desc 11",
    body: "body 11",
    tagList: ["test11", "test11"],
  },
  {
    title: "Setup article 12",
    description: "desc 12",
    body: "body 12",
    tagList: ["test12", "test12"],
  },
  {
    title: "Setup article 13",
    description: "desc 13",
    body: "body 13",
    tagList: ["test13", "test13"],
  },
  {
    title: "Setup article 14",
    description: "desc 14",
    body: "body 14",
    tagList: ["test14", "test14"],
  },
  {
    title: "Setup article 15",
    description: "desc 15",
    body: "body 15",
    tagList: ["test15", "test15"],
  },
  {
    title: "Setup article 16",
    description: "desc 16",
    body: "body 16",
    tagList: ["test16", "test16"],
  },
  {
    title: "Setup article 17",
    description: "desc 17",
    body: "body 17",
    tagList: ["test17", "test17"],
  },
  {
    title: "Setup article 18",
    description: "desc 18",
    body: "body 18",
    tagList: ["test18", "test18"],
  },
  {
    title: "Setup article 19",
    description: "desc 19",
    body: "body 19",
    tagList: ["test19", "test19"],
  },
  {
    title: "Setup article 20",
    description: "desc 20",
    body: "body 20",
    tagList: ["test20", "test20"],
  },
  {
    title: "Setup article 21",
    description: "desc 21",
    body: "body 21",
    tagList: ["test21", "test21"],
  },
];
